FROM node:14.17.0

WORKDIR /app

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.5.1/wait /wait
RUN chmod +x /wait

COPY package*.json /app/

RUN npm install

COPY . .

ENTRYPOINT [ "/app/test-deployment-workflow.sh" ]

CMD []
