---
apiVersion: v1
kind: Service
metadata:
    name: crawler-api
    labels:
        app: fleet
        type: crawler-api
        env: prod
spec:
    ports:
        - port: 3000
          name: entry
          protocol: TCP
    selector:
        app: fleet
        type: crawler-api
        env: prod
