apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: crawler-api-storage-pvc
spec:
    storageClassName: standard-storage
    resources:
        requests:
            storage: 10Gi
    accessModes:
        - ReadWriteOnce
