---
apiVersion: v1
kind: Service
metadata:
    name: metabase
    labels:
        app: fleet
        type: metabase
        env: prod
spec:
    ports:
        - port: 3000
          name: entry
          protocol: TCP
    selector:
        app: fleet
        type: metabase
        env: prod
