apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: metabase-storage-pvc
spec:
    storageClassName: ssd-storage
    resources:
        requests:
            storage: 15Gi
    accessModes:
        - ReadWriteOnce
