---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: ocr
spec:
    replicas: 1
    selector:
        matchLabels:
            app: fleet
            type: ocr
            env: staging
    template:
        metadata:
            labels:
                app: fleet
                type: ocr
                env: staging
        spec:
            containers:
                - image: eu.gcr.io/fleet-260107/ocr:beta
                  name: ocr
                  imagePullPolicy: Always
                  resources:
                      requests:
                          cpu: 10m
                  ports:
                      - containerPort: 3000
                        name: entry
                        protocol: TCP
                  livenessProbe:
                      httpGet:
                          path: /health
                          port: 3000
                      initialDelaySeconds: 15
                      periodSeconds: 10
                  readinessProbe:
                      httpGet:
                          path: /health
                          port: 3000
                      initialDelaySeconds: 15
                      periodSeconds: 10
