export const PERMISSIONS = {
    CreateProfile: { name: 'Create Profile', group: 'Profile' },
    ViewProfile: { name: 'View Profile', group: 'Profile' },
    ViewProfileLogs: { name: 'View Profile Logs', group: 'Profile' },
    EditProfile: { name: 'Edit Profile', group: 'Profile' },
    DeleteProfile: { name: 'Delete Profile', group: 'Profile' },

    ViewAccountRelation: { name: 'View Account Relation', group: 'Account Relation' },
    CreateAccountRelation: { name: 'Create Account Relation', group: 'Account Relation' },
    EditAccountRelation: { name: 'Edit Account Relation', group: 'Account Relation' },
    DeleteAccountRelation: { name: 'Delete Account Relation', group: 'Account Relation' },

    ViewUsers: { name: 'View Users', group: 'Users' },
    ViewUser: { name: 'View User', group: 'Users' },
    CreateUsers: { name: 'Create Users', group: 'Users' },
    EditUsers: { name: 'Edit Users', group: 'Users' },
    DeleteUsers: { name: 'Delete User', group: 'Users' },

    ViewContract: { name: 'View Contract', group: 'Contracts' },
    ViewContracts: { name: 'View Contracts', group: 'Contracts' },
    EditContract: { name: 'Edit Contract', group: 'Contracts' },
    DeleteContract: { name: 'Delete Contract', group: 'Contracts' },
    CreateContract: { name: 'Create Contract', group: 'Contracts' },

    ViewDocument: { name: 'View Document', group: 'Document' },
    DeleteDocument: { name: 'Delete Document', group: 'Document' },
    CreateDocument: { name: 'Create Document', group: 'Document' },
    EditDocument: { name: 'Edit Document', group: 'Document' },
    LinkDocument: { name: 'Link Document', group: 'Document' },

    ViewVehicles: { name: 'View Vehicles', group: 'Vehicles' },
    ViewVehicle: { name: 'View Vehicle', group: 'Vehicles' },
    ViewVehicleLogs: { name: 'View Vehicle Logs', group: 'Vehicles' },
    CreateVehicle: { name: 'Create Vehicle', group: 'Vehicles' },
    EditVehicles: { name: 'Edit Vehicle', group: 'Vehicles' },
    DeleteVehicles: { name: 'Delete Vehicle', group: 'Vehicles' },

    ViewInfringements: { name: 'View Infringements', group: 'Infringements' },
    ViewInfringement: { name: 'View Infringement', group: 'Infringements' },
    ViewInfringementLogs: { name: 'View Infringement Logs', group: 'Infringements' },
    CreateInfringement: { name: 'Create Infringement', group: 'Infringements' },
    EditInfringements: { name: 'Edit Infringement', group: 'Infringements' },
    DeleteInfringements: { name: 'Delete Infringement', group: 'Infringements' },
    AcknowledgeInfringement: { name: 'Acknowledge Infringement', group: 'Infringements' },
    AppealInfringement: { name: 'Appeal Infringement', group: 'Infringements' },
    RedirectInfringement: { name: 'Redirect Infringement', group: 'Infringements' },
    ApproveInfringement: { name: 'Approve Infringement', group: 'Infringements' },
    UnapproveInfringement: { name: 'Unapprove Infringement', group: 'Infringements' },
    GenerateRedirectionDocument: { name: 'Generate Redirection Document', group: 'Infringements' },
    
    ManualPayInfringement: { name: 'Manual Pay Infringement', group: 'Infringements' },
    PayInfringement: { name: 'Pay Infringement', group: 'Infringements' },
    ViewPastPayments: { name: 'View Past Payments', group: 'Infringements' },

    ViewInfringementNote: { name: 'View Infringement Note', group: 'Infringements' },
    ViewInfringementNotes: { name: 'View Infringement Notes', group: 'Infringements' },
    CreateInfringementNote: { name: 'Create Infringement Note', group: 'Infringements' },
    EditInfringementNote: { name: 'Edit Infringement Note', group: 'Infringements' },
    DeleteInfringementNote: { name: 'Delete Infringement Note', group: 'Infringements' },

    InfringementReporting: { name: 'Infringement Reporting', group: 'Reporting' },
    VehicleReporting: { name: 'Vehicle Reporting', group: 'Reporting' },
    FinanceReporting: { name: 'Finance Reporting', group: 'Reporting' },
    AccountReporting: { name: 'Account Reporting', group: 'Reporting' },
};
