export const vehicleManufacturers = [
    'Abarth',
    'AC',
    'ACMAT (France)',
    'AEC (UK)',
    'Albion Motors',
    'Albion (UK)',
    'Alexander Dennis',
    'Alfa Romeo',
    'Alpina',
    'Alpine',
    'Alternative Chassis Engineering',
    'AM General (Licensed production in USA)',
    'Ansair (1993 to 1997)',
    'Argyle (UK)',
    'Ariel',
    'Armstrong-Saurer (UK)',
    'Ascari',
    'Ashok Leyland',
    'Askam (Turkey)',
    'Associated Equipment Company',
    'Aston Martin',
    'Astra (Italy)',
    'Atkinson (UK)',
    'Audi',
    'Austin (UK)',
    'Australian Bus Manufacturing',
    'Automiesse (Belgium)',
    'Autosan',
    'Avia Trucks (Czech Republic)',
    'Avtomobilnoe Moskovskoe Obshchestvo (Russia)',
    'AWD (UK)',
    'Ayats',
    'Barkas (Germany)',
    'Baron (UK)',
    'Barreiros (Spain)',
    'BCI Bus',
    'Bean (UK)',
    'Beardmore (UK)',
    'Bedford Vehicles',
    'Bedford (UK)',
    'BelAZ (Belarus)',
    'Belkommunmash',
    'Belsize Motors (UK)',
    'Bentley',
    'Berliet',
    'Berliet-Tramagal (Portugal)',
    'Berna (Switzerland)',
    'Blue Bird Body Company (1948-1992)',
    'Blue Bird Corporation (1992–present)',
    'BMC (Turkey)',
    'BMW',
    'Borgward (Germany)',
    'BredaMenarinibus',
    'Bristol',
    'Bristol Commercial Vehicles',
    'British Motor Corporation (UK)',
    'Brossel (Belgium)',
    'Bruce-SN (UK)',
    'Bucegi (Romania)',
    'Bugatti',
    'Büssing (Germany)',
    'Bustech',
    'BYD Auto',
    'Byton',
    'Cacciamali 1996 to 1999',
    'Cadillac',
    'Caledon (UK)',
    'Carmichael (UK)',
    'Caterham',
    'Chance Coach',
    'Changan',
    'Chavdar (Bulgaria)',
    'Chenard-Walcker (France)',
    'Chevrolet',
    'Chrysler',
    'Citroen',
    'Cobus Industries',
    'Commer (UK)',
    'Corvette',
    'Crossley (UK)',
    'Crown-Ikarus',
    'CRRC',
    'ČSAO Čáslav',
    'Csepel (Hungary)',
    'Cupra',
    'Custom Bus',
    'DAC Trucks (Romania)',
    'Dacia',
    'Daewoo Bus',
    'DAF',
    'DAF Bus/VDL Bus',
    'DAF Trucks (Netherlands) (division of Paccar)',
    'Daihatsu',
    'Daimler',
    'Daimler AG (Germany)',
    'Dallara',
    'David Brown',
    'De Dion-Bouton (France)',
    'Dekstra Bus',
    'Delahaye (France)',
    'Dennis',
    'Dennis Bros',
    'Dennis Eagle (UK)',
    'Dennis Specialist Vehicles',
    'Dennis / TransBus / Alexander Dennis',
    'Dennis-Mann Egerton (UK)',
    'Dennison (Ireland)',
    'DesignLine Corporation',
    'DFSK',
    'Dodge',
    'Douglas (UK)',
    'DS',
    'Duple Coachbuilders',
    'Dutch Amphibious Transport Vehicles BV',
    'East Lancashire Coachbuilders',
    'Ebro (Spain)',
    'Edwin Foden Sons & Co',
    'Ekova',
    'Ekova',
    'El Detalle',
    'Elemental',
    'ELM Trucking(Germany)',
    'ELVO (Greece)',
    'Emgrand',
    'ERF (UK)',
    'Fabrika automobila Priboj',
    'FAP (Serbia)',
    'FAR Trucks (France)',
    'Faraday Future',
    'FBW (Switzerland)',
    'Ferrari',
    'Fiat',
    'Fisker',
    'Flxible',
    'Foden (UK)',
    'Ford',
    'Foremost',
    'Fowler (UK)',
    'Fraunhofer IVI',
    'Freightliner Trucks',
    'FTF Trucks (Netherlands)',
    'GA (Azerbaijan)',
    'Garner (UK)',
    'Garrett (UK)',
    'Gaz (Russia)',
    'Geely',
    'General Motors Truck & Coach',
    'Genesis',
    'Gilford (UK)',
    'Gillig Brothers (1940-1969)',
    'Gillig Corporation',
    'Ginaf (Netherlands)',
    'Ginetta',
    'GM Canada (1982-1987)',
    'Göppel',
    'Gräf & Stift (Austria)',
    'Great Wall',
    'Grube (Germany)',
    'Grumman',
    'Guy Motors',
    'Guy (UK)',
    'GV (UK)',
    'Halley (UK)',
    'Hallford (UK)',
    'Hanomag (Germany)',
    'Hardy (UK)',
    'Haulamatic (UK)',
    'Henschel (Germany)',
    'HHT (UK)',
    'Hino Motors',
    'Hispano-Suiza (Spain)',
    'Honda',
    'Horch (Germany)',
    'Hotchkiss (France)',
    'HSG (UK)',
    'Hummer',
    'Hyundai',
    'Hyundai Motor Company',
    'IFA (Germany)',
    'IIA - Industria Italiana Autobus S.p.A.',
    'IIA - Industria Italiana Autobus SpA',
    'Ikarbus',
    'Ikarus',
    'Ikarus Bus',
    'Infiniti',
    'International Harvester (1979-1986)',
    'Invicta',
    'Irisbus',
    'Irizar',
    'Isuzu',
    'Iveco',
    'Iveco Bus',
    'Jaguar',
    'Jeep',
    'Jelcz',
    'Jensen (UK)',
    'Kaelble (Germany)',
    'Kahn',
    'Kalmar (Poland)',
    'Kamaz (Russia)',
    'Karosa',
    'Karrier (UK)',
    'KAZ (Georgia)',
    'Kerr Stuart (UK)',
    'Kia Motors',
    'King Long',
    'Kode',
    'KrAZ (Ukraine)',
    'Kromhout (Netherlands)',
    'KTM',
    'Labourier (France)',
    'Lacre (UK)',
    'Lahden Autokori',
    'Lamborghini',
    'Lancia (Italy)',
    'Land Rover',
    'Latil (France)',
    'LAZ (Ukraine)',
    'LDV',
    'LDV Group',
    'Lexus',
    'Leyland Motors',
    'Leyland DAF (UK)',
    'LIAZ (Czech Republic, 1951–2002)',
    'Loheac (France)',
    'Lomount (UK)',
    'London General Omnibus Company',
    'Lorraine-Dietrich (France)',
    'Lotus',
    'Lviv Bus Factory',
    'Lykan',
    'Lynk & Co',
    'Madara (Bulgaria)',
    'Magirus (Germany)',
    'Mahendra Motor European (Germany)',
    'Mahindra',
    'MAN',
    'Manchester (UK)',
    'Mann (UK)',
    'Manufacturing Commercial Vehicles',
    'Marcos',
    'Marshall Bus',
    'Maserati',
    'Maudslay (UK)',
    'Mave Liptál',
    'Maybach',
    'MAZ (Belarus)',
    'Mazda',
    'McCurd (UK)',
    'MCI (1987-1993)',
    'McLaren',
    'MCV',
    'Mercedes',
    'Mercedes-Benz',
    'Metro Cammell Weymann',
    'MG',
    'Millennium Transit Services (2006–2009)',
    'Minerva (Belgium)',
    'MINI',
    'Minsk Automobile Plant',
    'Mitsubishi',
    'Mitsubishi Fuso Truck & Bus Corporation',
    'MOIA',
    'Morgan',
    'Morris (UK)',
    'Motor Coach Industries (1987–1995)',
    'Motor Traction (UK)',
    'Mowag (Switzerland)',
    'MTZ (Belarus)',
    'Multicar (Germany)',
    'Multiwheeler (UK)',
    'MZKT (Belarus)',
    'Namco (Greece)',
    'Navistar International',
    'Neobus (Serbia)',
    'Neoplan',
    'New Flyer Industries',
    'Nibus (Serbia)',
    'Nicolas (France)',
    'Nio',
    'Nissan',
    'Noble',
    'Nogebus',
    'Norde (UK)',
    'Northern Counties',
    'Nova Bus',
    'ÖAF (Austria)',
    'Officine Meccaniche Tortonesi (Italy)',
    'Officine Meccaniche (Italy)',
    'Opel (Germany)',
    'Optare',
    'Orion International',
    'Otokar',
    'Otosan (Turkey)',
    'Pagefield (UK)',
    'Panhard (France)',
    'Park Royal',
    'Paul Nutzfahrzeuge (Germany)',
    'Pegaso',
    'Pegaso (Spain)',
    'Perodua',
    'Peugeot',
    'Phoenix Bus (1997 to 1998)',
    'Plaxton',
    'Polaris',
    'Polestar',
    'Porsche',
    'Power Vehicle Innovation',
    'Praga',
    'Preslav (Bulgaria)',
    'Prevost',
    'Proctor (UK)',
    'Proton',
    'Qoros',
    'Quest (UK)',
    'Raba (Hungary)',
    'Radical',
    'Ranault',
    'Reeve Burgess',
    'Renault',
    'Riga Autobus Factory',
    'Robur (Germany)',
    'Rocar',
    'Rolls-Royce',
    'Roman (Romania)',
    'Rošero – P',
    'Rotinoff (UK)',
    'Rowe-Hillmaster (UK)',
    'Rutland (UK)',
    'Saab',
    'Saab-Scania and Metro Cammell Weymann',
    'Salvador Caetano',
    'Sanos',
    'Saurer (Switzerland)',
    'Saviem (France)',
    'Scammell (UK)',
    'Scania',
    'SD (UK)',
    'SEAT',
    'Seddon (UK)',
    'Sentinel (UK)',
    'Shefflex (UK)',
    'Sides (France)',
    'Simca (France)',
    'Sisu Auto (Finland)',
    'SKD Trade',
    'Skoda',
    'Škoda Transportation',
    'Slovbus',
    'Smart',
    'Solaris',
    'Solbus',
    'Somua (France)',
    'SOR Libchavy',
    'SRT',
    'SsangYong',
    'Star (Poland)',
    'Star (UK)',
    'Steyr (Austria)',
    'Straker-Squire (UK)',
    'Straussler (UK)',
    'Subaru',
    'Suzuki',
    'Tadano Faun GmbH (Germany)',
    'TAM (Slovenia)',
    'Tata Marcopolo',
    'Tata Motors',
    'Tatra',
    'TEDOM',
    'Temax (Greece)',
    'Temsa',
    'Terberg (Netherlands)',
    'Tesla',
    'Thomas Built Buses',
    'Thomas Harrington & Sons',
    'Thornycroft (UK)',
    'Tilling Stevens (UK)',
    'Titan (Germany)',
    'Tonar (Russia)',
    'Toyota',
    'TransBus',
    'Trident',
    'Trolza',
    'TVM (Slovenia)',
    'TVR',
    'TVS Motar France (France)',
    'TVW (UK)',
    'UD Trucks',
    'Unic (France)',
    'Unimog (Germany)',
    'Union (UK)',
    'Unipower (UK)',
    'Ural (Russia)',
    'URO (Spain)',
    'USG-Pitt (UK)',
    'Van Hool',
    'Van Hool',
    'Vanaja (Finland)',
    'Vauxhall',
    'VDL Berkhof',
    'VDL Bus & Coach',
    'Verheul (Netherlands)',
    'Volgren',
    'Volkswagen',
    'Volkswagen Caminhões e Ônibus',
    'Volvo',
    'Volvo Buses',
    'Vomag (Germany)',
    'Vulcan (UK)',
    'Walter Alexander Coachbuilders',
    'Western Flyer, Flyer Industries, New Flyer',
    'Westfield',
    'Willeme (France)',
    'Wrightbus',
    'Yarovit[1] (Russia)',
    'Yellow Coach (1940-1944)',
    'Yorkshire (UK)',
    'Youngman',
    'Yutong',
    'Zastava Trucks (Serbia)',
    'Zenos',
    'ZiL (Russia)',
    'Zwicky (UK)',
];
