---
apiVersion: v1
kind: Service
metadata:
    name: backend
    labels:
        app: fleet
        type: backend
        env: staging
spec:
    externalTrafficPolicy: Local
    type: LoadBalancer
    ports:
        - port: 8080
          name: entry
          protocol: TCP
    selector:
        app: fleet
        type: backend
        env: staging
