import { PERMISSIONS } from '@modules/shared/models/permissions.const';

export const ROLE_PERMISSIONS: { name: string; permissions: { name: string; group: string }[] }[] = [
    {
        name: 'System Administrator',
        permissions: Object.values(PERMISSIONS),
    },
    {
        name: 'Administrator',
        permissions: Object.values(PERMISSIONS),
    },
    {
        name: 'Manager',
        permissions: [
            PERMISSIONS.ViewVehicle,
            PERMISSIONS.ViewVehicles,
            PERMISSIONS.ViewVehicleLogs,
            PERMISSIONS.ViewInfringement,
            PERMISSIONS.ViewInfringements,
            PERMISSIONS.ViewInfringementLogs,
            PERMISSIONS.ViewUser,
            PERMISSIONS.ViewUsers,
            PERMISSIONS.ViewProfile,
            PERMISSIONS.ViewProfileLogs,
            PERMISSIONS.ViewPastPayments,
            PERMISSIONS.FinanceReporting,
            PERMISSIONS.InfringementReporting,
            PERMISSIONS.VehicleReporting,
            PERMISSIONS.AccountReporting,
            PERMISSIONS.ViewContract,
            PERMISSIONS.ViewContracts,
            PERMISSIONS.ViewDocument,
            PERMISSIONS.ViewInfringementNote,
            PERMISSIONS.ViewInfringementNotes,
        ],
    },
    {
        name: 'Fleet Manager',
        permissions: [
            PERMISSIONS.ViewVehicle,
            PERMISSIONS.ViewVehicles,
            PERMISSIONS.ViewVehicleLogs,
            PERMISSIONS.CreateVehicle,
            PERMISSIONS.EditVehicles,
            PERMISSIONS.ViewInfringement,
            PERMISSIONS.ViewInfringements,
            PERMISSIONS.ViewInfringementLogs,
            PERMISSIONS.CreateInfringement,
            PERMISSIONS.ApproveInfringement,
            PERMISSIONS.UnapproveInfringement,
            PERMISSIONS.ViewUser,
            PERMISSIONS.ViewUsers,
            PERMISSIONS.ViewProfile,
            PERMISSIONS.ViewProfileLogs,
            PERMISSIONS.ViewPastPayments,
            PERMISSIONS.InfringementReporting,
            PERMISSIONS.VehicleReporting,
            PERMISSIONS.CreateProfile,
            PERMISSIONS.EditProfile,
            PERMISSIONS.ViewContract,
            PERMISSIONS.ViewContracts,
            PERMISSIONS.CreateContract,
            PERMISSIONS.ViewDocument,
            PERMISSIONS.CreateDocument,
            PERMISSIONS.ViewInfringementNote,
            PERMISSIONS.ViewInfringementNotes,
            PERMISSIONS.CreateInfringementNote,
            PERMISSIONS.AccountReporting,
        ],
    },
    {
        name: 'Account Relation Manager',
        permissions: [
            //PERMISSIONS.ViewAccountRelation,
            PERMISSIONS.CreateAccountRelation,
            PERMISSIONS.EditAccountRelation,
            PERMISSIONS.DeleteAccountRelation,
        ],
    },
    {
        name: 'Finance Manager',
        permissions: [
            PERMISSIONS.ViewInfringement,
            PERMISSIONS.ViewInfringements,
            PERMISSIONS.ViewInfringementLogs,
            PERMISSIONS.ViewProfile,
            PERMISSIONS.ViewProfileLogs,
            PERMISSIONS.ViewPastPayments,
            PERMISSIONS.PayInfringement,
            PERMISSIONS.ApproveInfringement,
            PERMISSIONS.UnapproveInfringement,
            PERMISSIONS.AppealInfringement,
            PERMISSIONS.RedirectInfringement,
            PERMISSIONS.FinanceReporting,
            PERMISSIONS.InfringementReporting,
            PERMISSIONS.VehicleReporting,
            PERMISSIONS.ViewContract,
            PERMISSIONS.ViewContracts,
            PERMISSIONS.ViewDocument,
            PERMISSIONS.ViewVehicle,
            PERMISSIONS.ViewVehicles,
            PERMISSIONS.ManualPayInfringement,
            PERMISSIONS.ViewPastPayments,
            PERMISSIONS.AccountReporting,
        ],
    },
];
