---
apiVersion: v1
kind: Service
metadata:
    name: documentation
    labels:
        app: fleet
        type: documentation
        env: prod
spec:
    ports:
        - port: 3123
          name: entry
          protocol: TCP
    selector:
        app: fleet
        type: documentation
        env: prod
