apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: database-storage-pvc
spec:
    storageClassName: std-storage
    resources:
        requests:
            storage: 20Gi
    accessModes:
        - ReadWriteOnce
