apiVersion: apps/v1
kind: Deployment
metadata:
    name: database
spec:
    replicas: 1
    selector:
        matchLabels:
            app: fleet
            type: database
            env: staging
    template:
        metadata:
            labels:
                app: fleet
                type: database
                env: staging
        spec:
            containers:
                - image: postgres:11.5
                  name: database
                  ports:
                      - containerPort: 5432
                        name: entry
                        protocol: TCP
                  livenessProbe:
                      tcpSocket:
                          port: 5432
                      initialDelaySeconds: 5
                      periodSeconds: 10
                  readinessProbe:
                      tcpSocket:
                          port: 5432
                      initialDelaySeconds: 5
                      periodSeconds: 10
                  volumeMounts:
                      - name: storage
                        mountPath: /var/lib/postgresql/data
                        subPath: data
                  env:
                      - name: POSTGRES_USER
                        valueFrom:
                            secretKeyRef:
                                name: database
                                key: POSTGRES_USER
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: database
                                key: POSTGRES_PASSWORD
                      - name: POSTGRES_DB
                        valueFrom:
                            secretKeyRef:
                                name: database
                                key: POSTGRES_DB
            volumes:
                - name: storage
                  persistentVolumeClaim:
                      claimName: database-storage-pvc
