apiVersion: v1
kind: Service
metadata:
    name: database-ext
    labels:
        app: fleet
        type: database
        env: staging
spec:
    externalTrafficPolicy: Cluster
    type: LoadBalancer
    ports:
        - port: 5432
          name: entry
          protocol: TCP
          nodePort: 32000
    selector:
        app: fleet
        type: database
        env: staging
