apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: document-api-storage-pvc
spec:
    storageClassName: ssd-storage
    resources:
        requests:
            storage: 10Gi
    accessModes:
        - ReadWriteOnce
