apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: backend-storage-pvc
spec:
    storageClassName: ssd-storage
    resources:
        requests:
            storage: 30Gi
    accessModes:
        - ReadWriteOnce
