apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: redis-storage-pvc
spec:
    storageClassName: std-storage
    resources:
        requests:
            storage: 10Gi
    accessModes:
        - ReadWriteOnce
