version: '3.6'
services:
    backend:
        build:
            context: $PWD/../../../backend
            dockerfile: $PWD/backend/Dockerfile
        volumes:
            - ../../../backend/src:/app/src
            - ../../../backend/storage:/app/storage
            - ../../../backend/scripts:/app/scripts
            - ../../../backend/emails:/app/emails
            - ../../../backend/locales:/app/locales
        ports:
            - 8080
            - '9229:9229'
        depends_on:
            - database
            - redis
        env_file:
            - ./backend/.secrets
            - ./backend/.env
        environment:
            - FORCE_COLOR=1

    metabase:
        image: metabase/metabase
        ports:
            - '4400:3000'
        depends_on:
            - database
        volumes:
            - metabase-data:/metabase-data
        environment:
            - MB_DB_FILE=/metabase-data/metabase.db

    document-api:
        build:
            context: $PWD/../../../document-api
            dockerfile: $PWD/document-api/Dockerfile
        volumes:
            #            - document-api-data:/app/storage
            - ../../../document-api/src:/app/src
        ports:
            - '8080:8080'
        env_file:
            - ./document-api/.env
        environment:
            - FORCE_COLOR=1

    frontend:
        build:
            context: $PWD/../../../frontend
            dockerfile: $PWD/frontend/Dockerfile
        ports:
            - 4200
        depends_on:
            - backend
        volumes:
            - ../../../frontend/src:/app/src

    document-renderer:
        build:
            context: $PWD/../../../document-renderer
            dockerfile: $PWD/document-renderer/Dockerfile
        ports:
            - '4300:4300'
        depends_on:
            - backend
        volumes:
            - ../../../document-renderer:/app

    redis:
        image: redis
        ports:
            - '6379:6379'
        command: ['redis-server', '--appendonly', 'yes']
        volumes:
            - 'redis-data:/data'

    database:
        image: postgres:11.5
        ports:
            - '6001:5432'
        env_file:
            - ./database/.env
            - ./database/.secrets
        volumes:
            - 'db-data:/var/lib/postgresql/data'

    nginx:
        image: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - 3000:80
        depends_on:
            - backend

volumes:
    db-data:
    redis-data:
    document-api-data:
    metabase-data:
